"""empty message

Revision ID: d766145f0e1e
Revises: dd620fc99cc3
Create Date: 2022-08-04 09:37:10.599739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd766145f0e1e'
down_revision = 'dd620fc99cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('show', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    op.alter_column('artist_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
