"""add new columns and relationship

Revision ID: dd620fc99cc3
Revises: 556f9b3cce59
Create Date: 2022-08-03 23:26:46.045905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd620fc99cc3'
down_revision = '556f9b3cce59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_genres', 'id')
    op.drop_column('venue_genres', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genres', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('artist_genres', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
